---
- role: andrewrothstein.gcc-toolbox
  version: v1.1.5
- role: andrewrothstein.go-dev
  version: v3.0.2
- role: andrewrothstein.goreleaser
  version: v2.1.14
- role: andrewrothstein.jq
  version: v1.0.8
- role: andrewrothstein.hashi
  version: v0.3.9
