name: ansible-playbook-tags
on:
  push:
    tags:
      - '*'
jobs:
  ## run build ###################################################
  # begin - build-debian_bookworm-slim-linux/amd64
  a244d78324ff2408b74f026c5b01d206e00c4d28e75bf26bb2692a63f008ed982:
    name: debian_bookworm-slim,linux/amd64
    runs-on: ubuntu-latest
    steps:
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: yq=version
        run: yq --version
      
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          export PATH=$(pwd)/bin:$PATH
        # uses: arduino/setup-task@v2
        # with:
        #   version: 3.35.1
        #   repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: task=version
        run: ./bin/task --version
      - name: checkout=taskfiles@feature/arm
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
          ref: feature/arm
      
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: task=tags
        run: |
          build='{"os":"debian_bookworm-slim","platforms":["linux/amd64","linux/arm64"]}'
          task -t ./taskfiles/tasks/containers/ansible.yml \
            build \
            build=${build} \
            platform=linux/amd64 \
            target_tag=${{ github.ref_name }} \
            is_tag=true
  # end - build-debian_bookworm-slim-linux/amd64
  # begin - build-debian_bookworm-slim-linux/arm64
  a98a0e548a6229f57214d52c4bf203d5b7ec85e46d4b8c9f979700d29c7319d91:
    name: debian_bookworm-slim,linux/arm64
    runs-on: arm64
    steps:
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: yq=version
        run: yq --version
      
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          export PATH=$(pwd)/bin:$PATH
        # uses: arduino/setup-task@v2
        # with:
        #   version: 3.35.1
        #   repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: task=version
        run: ./bin/task --version
      - name: checkout=taskfiles@feature/arm
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
          ref: feature/arm
      
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: task=tags
        run: |
          build='{"os":"debian_bookworm-slim","platforms":["linux/amd64","linux/arm64"]}'
          task -t ./taskfiles/tasks/containers/ansible.yml \
            build \
            build=${build} \
            platform=linux/arm64 \
            target_tag=${{ github.ref_name }} \
            is_tag=true
  # end - build-debian_bookworm-slim-linux/arm64
  ## manifest tool ###############################################
  # begin - manifest-debian_bookworm-slim
  a7a8cbed9d9a2e94fb56e35155cc8fe61fbc1f6c89357b7eb10b509068e63acec:
    name: debian_bookworm-slim
    runs-on: ubuntu-latest
    needs:
      # requires first character to be a letter
      # use sha256 of build os and platform
      - a244d78324ff2408b74f026c5b01d206e00c4d28e75bf26bb2692a63f008ed982
      # requires first character to be a letter
      # use sha256 of build os and platform
      - a98a0e548a6229f57214d52c4bf203d5b7ec85e46d4b8c9f979700d29c7319d91
    steps:
      - name: test
        run: echo "test"
  # end - manifest-debian_bookworm-slim
