name: ansible-playbook-branches
on:
  - push
  - workflow_dispatch
jobs:
  config-yaml:
    name: config.yaml
    runs-on: arm64
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: yq=version
        run: yq --version
      
      - name: jq=1.7
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
      
      - name: export=config
        id: config
        run: echo "config=$(yq -oj '.' config.yaml | jq -cr)" >> $GITHUB_OUTPUT
  
  matrix-builds:
    name: ${{ matrix.build.os }}-${{ matrix.build.arch }}
    permissions: write-all
    runs-on: ${{ matrix.build.runs_on }}
    needs: config-yaml
    strategy:
      fail-fast: false
      matrix:
        build: ${{ fromJSON(needs.config-yaml.outputs.config).builds }}
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          export PATH=$(pwd)/bin:$PATH
      - name: task=version
        run: ./bin/task --version
      - name: checkout=taskfiles@feature/arm
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
          ref: feature/arm
      
      # https://github.com/chrisdickinson/setup-yq/blob/latest/action.yml
      - uses: chrisdickinson/setup-yq@v1.0.1
        name: yq=v4.43.1
        with:
          yq-version: v4.43.1
      - name: yq=version
        run: yq --version
      
      - name: jq=1.7
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
      
      - uses: docker/login-action@v3
        name: login=ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: task=branches
        run: |
          build=$(echo '${{ toJson(matrix.build) }}'  | jq -rc '.')
          ./bin/task -t ./taskfiles/tasks/containers/ansible.yml \
            build \
            build=${build} \
            target_tag=latest \
            is_tag=false
      
